# ADVANCED SQL PROJECT

PROJECT: SALES MANAGEMENT DATABASE

DATABASE: AdvancedSalesDB

This project covers:

1. CREATE DATABASE
2. CREATE TABLE
3. INSERT DATA
4. INNER JOIN
5. GROUP BY
6. HAVING
7. SUBQUERY
8. CTE
9. RANK()
10. DENSE_RANK()
11. ROW_NUMBER()
12. PARTITION BY
13. CASE
14. EXISTS
15. NOT EXISTS
16. LAG()
17. RUNNING TOTAL
18. DISTINCT
19. MULTIPLE JOINS
20. TOP-N ANALYSIS

==================================================

1. CREATE DATABASE
   ==================================================

CREATE DATABASE AdvancedSalesDB;
GO

USE AdvancedSalesDB;
GO

==================================================
2. CREATE CUSTOMERS TABLE
=========================

CREATE TABLE Customers
(
CustomerID INT PRIMARY KEY,
CustomerName VARCHAR(100),
City VARCHAR(50),
State VARCHAR(50),
SignupDate DATE
);

==================================================
3. CREATE PRODUCTS TABLE
========================

CREATE TABLE Products
(
ProductID INT PRIMARY KEY,
ProductName VARCHAR(100),
Category VARCHAR(50),
Price DECIMAL(10,2)
);

==================================================
4. CREATE ORDERS TABLE
======================

CREATE TABLE Orders
(
OrderID INT PRIMARY KEY,
CustomerID INT,
OrderDate DATE,
Status VARCHAR(20),

```
FOREIGN KEY (CustomerID)
REFERENCES Customers(CustomerID)
```

);

==================================================
5. CREATE ORDERDETAILS TABLE
============================

CREATE TABLE OrderDetails
(
OrderDetailID INT PRIMARY KEY,
OrderID INT,
ProductID INT,
Quantity INT,

```
FOREIGN KEY (OrderID)
REFERENCES Orders(OrderID),

FOREIGN KEY (ProductID)
REFERENCES Products(ProductID)
```

);

==================================================
6. INSERT CUSTOMERS DATA
========================

INSERT INTO Customers
(CustomerID, CustomerName, City, State, SignupDate)
VALUES
(1, 'Amit Sharma', 'Mumbai', 'Maharashtra', '2025-01-10'),
(2, 'Rahul Patil', 'Pune', 'Maharashtra', '2025-01-15'),
(3, 'Sneha Khan', 'Aurangabad', 'Maharashtra', '2025-02-05'),
(4, 'Priya Singh', 'Delhi', 'Delhi', '2025-02-18'),
(5, 'Arjun Mehta', 'Ahmedabad', 'Gujarat', '2025-03-02'),
(6, 'Neha Joshi', 'Nashik', 'Maharashtra', '2025-03-15'),
(7, 'Vikas Verma', 'Bangalore', 'Karnataka', '2025-04-01'),
(8, 'Pooja Desai', 'Surat', 'Gujarat', '2025-04-10'),
(9, 'Rohit Kapoor', 'Jaipur', 'Rajasthan', '2025-05-12'),
(10, 'Sana Shaikh', 'Hyderabad', 'Telangana', '2025-05-20');

==================================================
7. INSERT PRODUCTS DATA
=======================

INSERT INTO Products
(ProductID, ProductName, Category, Price)
VALUES
(101, 'Laptop', 'Electronics', 65000),
(102, 'Smartphone', 'Electronics', 30000),
(103, 'Headphones', 'Electronics', 2500),
(104, 'Keyboard', 'Accessories', 1500),
(105, 'Mouse', 'Accessories', 800),
(106, 'Monitor', 'Electronics', 18000),
(107, 'Office Chair', 'Furniture', 12000),
(108, 'Desk', 'Furniture', 15000),
(109, 'Bookshelf', 'Furniture', 9000),
(110, 'Printer', 'Electronics', 12000),
(111, 'Webcam', 'Accessories', 3500),
(112, 'Tablet', 'Electronics', 22000);

==================================================
8. INSERT ORDERS DATA
=====================

INSERT INTO Orders
(OrderID, CustomerID, OrderDate, Status)
VALUES
(1001, 1, '2025-06-01', 'Completed'),
(1002, 2, '2025-06-02', 'Completed'),
(1003, 3, '2025-06-03', 'Completed'),
(1004, 4, '2025-06-04', 'Cancelled'),
(1005, 5, '2025-06-05', 'Completed'),
(1006, 1, '2025-06-06', 'Completed'),
(1007, 6, '2025-06-07', 'Completed'),
(1008, 7, '2025-06-08', 'Pending'),
(1009, 8, '2025-06-09', 'Completed'),
(1010, 9, '2025-06-10', 'Completed'),
(1011, 10, '2025-06-11', 'Completed'),
(1012, 2, '2025-06-12', 'Completed'),
(1013, 3, '2025-06-13', 'Completed'),
(1014, 5, '2025-06-14', 'Completed'),
(1015, 7, '2025-06-15', 'Completed');

==================================================
9. INSERT ORDER DETAILS DATA
============================

INSERT INTO OrderDetails
(OrderDetailID, OrderID, ProductID, Quantity)
VALUES
(1, 1001, 101, 1),
(2, 1001, 103, 2),
(3, 1002, 102, 1),
(4, 1002, 105, 2),
(5, 1003, 104, 1),
(6, 1003, 106, 1),
(7, 1004, 101, 1),
(8, 1005, 107, 2),
(9, 1005, 108, 1),
(10, 1006, 102, 2),
(11, 1006, 111, 1),
(12, 1007, 109, 1),
(13, 1007, 105, 3),
(14, 1008, 110, 1),
(15, 1008, 103, 2),
(16, 1009, 101, 1),
(17, 1009, 104, 2),
(18, 1010, 112, 2),
(19, 1010, 105, 1),
(20, 1011, 106, 2),
(21, 1011, 103, 1),
(22, 1012, 108, 1),
(23, 1012, 107, 1),
(24, 1013, 102, 1),
(25, 1013, 112, 1),
(26, 1014, 101, 1),
(27, 1014, 111, 2),
(28, 1015, 110, 1),
(29, 1015, 106, 1),
(30, 1015, 105, 2);

==================================================
10. ADVANCED SQL QUESTIONS & SOLUTIONS
======================================

## QUESTION 1

Find the total sales generated by each customer.

SOLUTION:

SELECT
c.CustomerID,
c.CustomerName,
SUM(od.Quantity * p.Price) AS TotalSales
FROM Customers c
JOIN Orders o
ON c.CustomerID = o.CustomerID
JOIN OrderDetails od
ON o.OrderID = od.OrderID
JOIN Products p
ON od.ProductID = p.ProductID
WHERE o.Status = 'Completed'
GROUP BY
c.CustomerID,
c.CustomerName
ORDER BY TotalSales DESC;

## QUESTION 2

Find customers whose total sales are greater than 50,000.

SOLUTION:

SELECT
c.CustomerName,
SUM(od.Quantity * p.Price) AS TotalSales
FROM Customers c
JOIN Orders o
ON c.CustomerID = o.CustomerID
JOIN OrderDetails od
ON o.OrderID = od.OrderID
JOIN Products p
ON od.ProductID = p.ProductID
WHERE o.Status = 'Completed'
GROUP BY c.CustomerName
HAVING SUM(od.Quantity * p.Price) > 50000;

## QUESTION 3

Find the top 3 customers based on total sales.

SOLUTION:

SELECT TOP 3
c.CustomerName,
SUM(od.Quantity * p.Price) AS TotalSales
FROM Customers c
JOIN Orders o
ON c.CustomerID = o.CustomerID
JOIN OrderDetails od
ON o.OrderID = od.OrderID
JOIN Products p
ON od.ProductID = p.ProductID
WHERE o.Status = 'Completed'
GROUP BY c.CustomerName
ORDER BY TotalSales DESC;

## QUESTION 4

Rank customers based on their total sales.

SOLUTION:

SELECT
c.CustomerName,
SUM(od.Quantity * p.Price) AS TotalSales,

```
RANK() OVER
(
    ORDER BY SUM(od.Quantity * p.Price) DESC
) AS SalesRank
```

FROM Customers c
JOIN Orders o
ON c.CustomerID = o.CustomerID
JOIN OrderDetails od
ON o.OrderID = od.OrderID
JOIN Products p
ON od.ProductID = p.ProductID

WHERE o.Status = 'Completed'

GROUP BY c.CustomerName;

## QUESTION 5

Find the highest-selling product based on quantity.

SOLUTION:

SELECT TOP 1
p.ProductName,
SUM(od.Quantity) AS TotalQuantity
FROM Products p
JOIN OrderDetails od
ON p.ProductID = od.ProductID
JOIN Orders o
ON od.OrderID = o.OrderID
WHERE o.Status = 'Completed'
GROUP BY p.ProductName
ORDER BY TotalQuantity DESC;

## QUESTION 6

Find the highest-selling product in each category.

SOLUTION:

WITH ProductSales AS
(
SELECT
p.Category,
p.ProductName,
SUM(od.Quantity * p.Price) AS TotalSales
FROM Products p
JOIN OrderDetails od
ON p.ProductID = od.ProductID
JOIN Orders o
ON od.OrderID = o.OrderID
WHERE o.Status = 'Completed'
GROUP BY
p.Category,
p.ProductName
),
RankedProducts AS
(
SELECT *,
RANK() OVER
(
PARTITION BY Category
ORDER BY TotalSales DESC
) AS ProductRank
FROM ProductSales
)
SELECT
Category,
ProductName,
TotalSales
FROM RankedProducts
WHERE ProductRank = 1;

## QUESTION 7

Find customers who never placed an order.

SOLUTION:

SELECT
c.CustomerID,
c.CustomerName
FROM Customers c
WHERE NOT EXISTS
(
SELECT 1
FROM Orders o
WHERE o.CustomerID = c.CustomerID
);

## QUESTION 8

Find products that were never sold in a completed order.

SOLUTION:

SELECT
p.ProductID,
p.ProductName
FROM Products p
WHERE NOT EXISTS
(
SELECT 1
FROM OrderDetails od
JOIN Orders o
ON od.OrderID = o.OrderID
WHERE od.ProductID = p.ProductID
AND o.Status = 'Completed'
);

## QUESTION 9

Find customers whose sales are above the average customer sales.

SOLUTION:

WITH CustomerSales AS
(
SELECT
c.CustomerID,
c.CustomerName,
SUM(od.Quantity * p.Price) AS TotalSales
FROM Customers c
JOIN Orders o
ON c.CustomerID = o.CustomerID
JOIN OrderDetails od
ON o.OrderID = od.OrderID
JOIN Products p
ON od.ProductID = p.ProductID
WHERE o.Status = 'Completed'
GROUP BY
c.CustomerID,
c.CustomerName
)
SELECT *
FROM CustomerSales
WHERE TotalSales >
(
SELECT AVG(TotalSales)
FROM CustomerSales
);

## QUESTION 10

Classify customers based on their total sales.

High Value   = Sales >= 80,000
Medium Value = Sales >= 40,000
Low Value    = Sales < 40,000

SOLUTION:

WITH CustomerSales AS
(
SELECT
c.CustomerID,
c.CustomerName,
SUM(od.Quantity * p.Price) AS TotalSales
FROM Customers c
JOIN Orders o
ON c.CustomerID = o.CustomerID
JOIN OrderDetails od
ON o.OrderID = od.OrderID
JOIN Products p
ON od.ProductID = p.ProductID
WHERE o.Status = 'Completed'
GROUP BY
c.CustomerID,
c.CustomerName
)
SELECT
CustomerName,
TotalSales,

```
CASE
    WHEN TotalSales >= 80000 THEN 'High Value'
    WHEN TotalSales >= 40000 THEN 'Medium Value'
    ELSE 'Low Value'
END AS CustomerCategory
```

FROM CustomerSales;

## QUESTION 11

Find total sales month-wise.

SOLUTION:

SELECT
YEAR(o.OrderDate) AS SalesYear,
MONTH(o.OrderDate) AS SalesMonth,
SUM(od.Quantity * p.Price) AS TotalSales
FROM Orders o
JOIN OrderDetails od
ON o.OrderID = od.OrderID
JOIN Products p
ON od.ProductID = p.ProductID
WHERE o.Status = 'Completed'
GROUP BY
YEAR(o.OrderDate),
MONTH(o.OrderDate)
ORDER BY
SalesYear,
SalesMonth;

## QUESTION 12

Calculate the running total of sales.

SOLUTION:

WITH DailySales AS
(
SELECT
o.OrderDate,
SUM(od.Quantity * p.Price) AS DailySales
FROM Orders o
JOIN OrderDetails od
ON o.OrderID = od.OrderID
JOIN Products p
ON od.ProductID = p.ProductID
WHERE o.Status = 'Completed'
GROUP BY o.OrderDate
)
SELECT
OrderDate,
DailySales,

```
SUM(DailySales) OVER
(
    ORDER BY OrderDate
    ROWS BETWEEN UNBOUNDED PRECEDING
    AND CURRENT ROW
) AS RunningTotal
```

FROM DailySales
ORDER BY OrderDate;

## QUESTION 13

Find the previous day's sales using LAG().

SOLUTION:

WITH DailySales AS
(
SELECT
o.OrderDate,
SUM(od.Quantity * p.Price) AS DailySales
FROM Orders o
JOIN OrderDetails od
ON o.OrderID = od.OrderID
JOIN Products p
ON od.ProductID = p.ProductID
WHERE o.Status = 'Completed'
GROUP BY o.OrderDate
)
SELECT
OrderDate,
DailySales,

```
LAG(DailySales) OVER
(
    ORDER BY OrderDate
) AS PreviousDaySales
```

FROM DailySales;

## QUESTION 14

Find the sales difference between the current day and previous day.

SOLUTION:

WITH DailySales AS
(
SELECT
o.OrderDate,
SUM(od.Quantity * p.Price) AS DailySales
FROM Orders o
JOIN OrderDetails od
ON o.OrderID = od.OrderID
JOIN Products p
ON od.ProductID = p.ProductID
WHERE o.Status = 'Completed'
GROUP BY o.OrderDate
),
SalesComparison AS
(
SELECT
OrderDate,
DailySales,
LAG(DailySales) OVER
(
ORDER BY OrderDate
) AS PreviousDaySales
FROM DailySales
)
SELECT
OrderDate,
DailySales,
PreviousDaySales,
DailySales - PreviousDaySales AS SalesDifference
FROM SalesComparison;

## QUESTION 15

Rank products within each category.

SOLUTION:

SELECT
p.Category,
p.ProductName,
SUM(od.Quantity * p.Price) AS TotalSales,

```
DENSE_RANK() OVER
(
    PARTITION BY p.Category
    ORDER BY SUM(od.Quantity * p.Price) DESC
) AS CategoryRank
```

FROM Products p
JOIN OrderDetails od
ON p.ProductID = od.ProductID
JOIN Orders o
ON od.OrderID = o.OrderID

WHERE o.Status = 'Completed'

GROUP BY
p.Category,
p.ProductName;

## QUESTION 16

Find customers who purchased a Laptop.

SOLUTION:

SELECT DISTINCT
c.CustomerName
FROM Customers c
JOIN Orders o
ON c.CustomerID = o.CustomerID
JOIN OrderDetails od
ON o.OrderID = od.OrderID
JOIN Products p
ON od.ProductID = p.ProductID
WHERE p.ProductName = 'Laptop'
AND o.Status = 'Completed';

## QUESTION 17

Find customers who purchased both Laptop and Smartphone.

SOLUTION:

SELECT
c.CustomerName
FROM Customers c
JOIN Orders o
ON c.CustomerID = o.CustomerID
JOIN OrderDetails od
ON o.OrderID = od.OrderID
JOIN Products p
ON od.ProductID = p.ProductID
WHERE p.ProductName IN ('Laptop', 'Smartphone')
AND o.Status = 'Completed'
GROUP BY c.CustomerName
HAVING COUNT(DISTINCT p.ProductName) = 2;

## QUESTION 18

Find the average order value.

SOLUTION:

WITH OrderSales AS
(
SELECT
o.OrderID,
SUM(od.Quantity * p.Price) AS OrderValue
FROM Orders o
JOIN OrderDetails od
ON o.OrderID = od.OrderID
JOIN Products p
ON od.ProductID = p.ProductID
WHERE o.Status = 'Completed'
GROUP BY o.OrderID
)
SELECT
AVG(OrderValue) AS AverageOrderValue
FROM OrderSales;

## QUESTION 19

Find the second-highest customer based on total sales.

SOLUTION:

WITH CustomerSales AS
(
SELECT
c.CustomerName,
SUM(od.Quantity * p.Price) AS TotalSales
FROM Customers c
JOIN Orders o
ON c.CustomerID = o.CustomerID
JOIN OrderDetails od
ON o.OrderID = od.OrderID
JOIN Products p
ON od.ProductID = p.ProductID
WHERE o.Status = 'Completed'
GROUP BY c.CustomerName
),
RankedCustomers AS
(
SELECT
CustomerName,
TotalSales,
DENSE_RANK() OVER
(
ORDER BY TotalSales DESC
) AS SalesRank
FROM CustomerSales
)
SELECT
CustomerName,
TotalSales
FROM RankedCustomers
WHERE SalesRank = 2;

## QUESTION 20

Find the top 2 products from each category.

SOLUTION:

WITH ProductSales AS
(
SELECT
p.Category,
p.ProductName,
SUM(od.Quantity * p.Price) AS TotalSales
FROM Products p
JOIN OrderDetails od
ON p.ProductID = od.ProductID
JOIN Orders o
ON od.OrderID = o.OrderID
WHERE o.Status = 'Completed'
GROUP BY
p.Category,
p.ProductName
),
RankedProducts AS
(
SELECT
Category,
ProductName,
TotalSales,

```
    ROW_NUMBER() OVER
    (
        PARTITION BY Category
        ORDER BY TotalSales DESC
    ) AS ProductRank

FROM ProductSales
```

)
SELECT
Category,
ProductName,
TotalSales,
ProductRank
FROM RankedProducts
WHERE ProductRank <= 2
ORDER BY
Category,
ProductRank;

==================================================
END OF ADVANCED SQL PROJECT
===========================

# SKILLS PRACTICED

CREATE DATABASE
CREATE TABLE
PRIMARY KEY
FOREIGN KEY
INSERT
INNER JOIN
GROUP BY
HAVING
ORDER BY
TOP
DISTINCT
SUBQUERY
CTE
CASE
EXISTS
NOT EXISTS
RANK()
DENSE_RANK()
ROW_NUMBER()
PARTITION BY
LAG()
SUM() OVER()
RUNNING TOTAL
TOP-N ANALYSIS
MULTIPLE TABLE JOINS
SALES ANALYSIS
CUSTOMER ANALYSIS
PRODUCT ANALYSIS
